# Generated by Django 3.0.5 on 2024-09-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_policycategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PolicyCategory',
        ),
    ]
