# Generated by Django 3.0.5 on 2024-09-29 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_delete_policycategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyrecord',
            old_name='Policy',
            new_name='policy',
        ),
        migrations.AddField(
            model_name='policy',
            name='renewal_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
