# Generated by Django 3.0.5 on 2024-09-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_auto_20240929_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='renewal_date',
        ),
    ]
