# Generated by Django 3.0.5 on 2024-09-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_remove_policy_renewal_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyrecord',
            old_name='policy',
            new_name='Policy',
        ),
    ]
